// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notifications struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	TenantID   string           `json:"tenant_id"`
	TemplateID string           `json:"template_id"`
	Type       string           `json:"type"`
	Status     string           `json:"status"`
	Data       []byte           `json:"data"`
	SentAt     pgtype.Timestamp `json:"sent_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type Templates struct {
	ID        string           `json:"id"`
	TenantID  string           `json:"tenant_id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	Subject   pgtype.Text      `json:"subject"`
	Content   string           `json:"content"`
	Variables []byte           `json:"variables"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
