// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package db

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id, tenant_id, template_id, type, status, data
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, tenant_id, template_id, type, status, data, sent_at, created_at, updated_at, deleted_at
`

type CreateNotificationParams struct {
	UserID     string `json:"user_id"`
	TenantID   string `json:"tenant_id"`
	TemplateID string `json:"template_id"`
	Type       string `json:"type"`
	Status     string `json:"status"`
	Data       []byte `json:"data"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notifications, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.TenantID,
		arg.TemplateID,
		arg.Type,
		arg.Status,
		arg.Data,
	)
	var i Notifications
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TemplateID,
		&i.Type,
		&i.Status,
		&i.Data,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, tenant_id, template_id, type, status, data, sent_at, created_at, updated_at, deleted_at FROM notifications
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetNotification(ctx context.Context, id string) (Notifications, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notifications
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TemplateID,
		&i.Type,
		&i.Status,
		&i.Data,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, tenant_id, template_id, type, status, data, sent_at, created_at, updated_at, deleted_at FROM notifications
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNotificationByID(ctx context.Context, id string) (Notifications, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notifications
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TemplateID,
		&i.Type,
		&i.Status,
		&i.Data,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotificationsByTemplateID = `-- name: GetNotificationsByTemplateID :many
SELECT id, user_id, tenant_id, template_id, type, status, data, sent_at, created_at, updated_at, deleted_at FROM notifications
WHERE template_id = $1 
AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsByTemplateIDParams struct {
	TemplateID string `json:"template_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetNotificationsByTemplateID(ctx context.Context, arg GetNotificationsByTemplateIDParams) ([]Notifications, error) {
	rows, err := q.db.Query(ctx, getNotificationsByTemplateID, arg.TemplateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notifications{}
	for rows.Next() {
		var i Notifications
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.TemplateID,
			&i.Type,
			&i.Status,
			&i.Data,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingNotifications = `-- name: GetPendingNotifications :many
SELECT id, user_id, tenant_id, template_id, type, status, data, sent_at, created_at, updated_at, deleted_at FROM notifications
WHERE status = 'PENDING' 
AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingNotifications(ctx context.Context, limit int32) ([]Notifications, error) {
	rows, err := q.db.Query(ctx, getPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notifications{}
	for rows.Next() {
		var i Notifications
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.TemplateID,
			&i.Type,
			&i.Status,
			&i.Data,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByTenantID = `-- name: ListNotificationsByTenantID :many
SELECT id, user_id, tenant_id, template_id, type, status, data, sent_at, created_at, updated_at, deleted_at FROM notifications
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByTenantIDParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListNotificationsByTenantID(ctx context.Context, arg ListNotificationsByTenantIDParams) ([]Notifications, error) {
	rows, err := q.db.Query(ctx, listNotificationsByTenantID, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notifications{}
	for rows.Next() {
		var i Notifications
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.TemplateID,
			&i.Type,
			&i.Status,
			&i.Data,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT id, user_id, tenant_id, template_id, type, status, data, sent_at, created_at, updated_at, deleted_at FROM notifications
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notifications, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notifications{}
	for rows.Next() {
		var i Notifications
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.TemplateID,
			&i.Type,
			&i.Status,
			&i.Data,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNotification = `-- name: SoftDeleteNotification :exec
UPDATE notifications
SET 
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteNotification(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteNotification, id)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notifications
SET 
    status = $2,
    sent_at = CASE WHEN $2 = 'SENT' THEN CURRENT_TIMESTAMP ELSE sent_at END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, tenant_id, template_id, type, status, data, sent_at, created_at, updated_at, deleted_at
`

type UpdateNotificationStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notifications, error) {
	row := q.db.QueryRow(ctx, updateNotificationStatus, arg.ID, arg.Status)
	var i Notifications
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TemplateID,
		&i.Type,
		&i.Status,
		&i.Data,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
