// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notifications, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Templates, error)
	GetNotification(ctx context.Context, id string) (Notifications, error)
	GetNotificationByID(ctx context.Context, id string) (Notifications, error)
	GetNotificationsByTemplateID(ctx context.Context, arg GetNotificationsByTemplateIDParams) ([]Notifications, error)
	GetPendingNotifications(ctx context.Context, limit int32) ([]Notifications, error)
	GetTemplateByID(ctx context.Context, id string) (Templates, error)
	GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (Templates, error)
	ListNotificationsByTenantID(ctx context.Context, arg ListNotificationsByTenantIDParams) ([]Notifications, error)
	ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notifications, error)
	ListTemplatesByTenantID(ctx context.Context, arg ListTemplatesByTenantIDParams) ([]Templates, error)
	ListTemplatesByType(ctx context.Context, arg ListTemplatesByTypeParams) ([]Templates, error)
	SearchTemplates(ctx context.Context, arg SearchTemplatesParams) ([]Templates, error)
	SoftDeleteNotification(ctx context.Context, id string) error
	SoftDeleteTemplate(ctx context.Context, id string) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notifications, error)
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Templates, error)
}

var _ Querier = (*Queries)(nil)
