// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (
    tenant_id,
    name,
    type,
    subject,
    content,
    variables
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, name, type, subject, content, variables, created_at, updated_at, deleted_at
`

type CreateTemplateParams struct {
	TenantID  string      `json:"tenant_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Subject   pgtype.Text `json:"subject"`
	Content   string      `json:"content"`
	Variables []byte      `json:"variables"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Templates, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Subject,
		arg.Content,
		arg.Variables,
	)
	var i Templates
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Subject,
		&i.Content,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, tenant_id, name, type, subject, content, variables, created_at, updated_at, deleted_at FROM templates
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTemplateByID(ctx context.Context, id string) (Templates, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i Templates
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Subject,
		&i.Content,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, tenant_id, name, type, subject, content, variables, created_at, updated_at, deleted_at FROM templates
WHERE tenant_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetTemplateByNameParams struct {
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (Templates, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, arg.TenantID, arg.Name)
	var i Templates
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Subject,
		&i.Content,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTemplatesByTenantID = `-- name: ListTemplatesByTenantID :many
SELECT id, tenant_id, name, type, subject, content, variables, created_at, updated_at, deleted_at FROM templates
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTemplatesByTenantIDParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListTemplatesByTenantID(ctx context.Context, arg ListTemplatesByTenantIDParams) ([]Templates, error) {
	rows, err := q.db.Query(ctx, listTemplatesByTenantID, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Templates{}
	for rows.Next() {
		var i Templates
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Subject,
			&i.Content,
			&i.Variables,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByType = `-- name: ListTemplatesByType :many
SELECT id, tenant_id, name, type, subject, content, variables, created_at, updated_at, deleted_at FROM templates
WHERE tenant_id = $1 AND type = $2 AND deleted_at IS NULL
ORDER BY name ASC
LIMIT $3 OFFSET $4
`

type ListTemplatesByTypeParams struct {
	TenantID string `json:"tenant_id"`
	Type     string `json:"type"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListTemplatesByType(ctx context.Context, arg ListTemplatesByTypeParams) ([]Templates, error) {
	rows, err := q.db.Query(ctx, listTemplatesByType,
		arg.TenantID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Templates{}
	for rows.Next() {
		var i Templates
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Subject,
			&i.Content,
			&i.Variables,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTemplates = `-- name: SearchTemplates :many
SELECT id, tenant_id, name, type, subject, content, variables, created_at, updated_at, deleted_at FROM templates
WHERE tenant_id = $1 
AND deleted_at IS NULL
AND (
    name ILIKE '%' || $2 || '%'
    OR subject ILIKE '%' || $2 || '%'
)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchTemplatesParams struct {
	TenantID string      `json:"tenant_id"`
	Column2  pgtype.Text `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) SearchTemplates(ctx context.Context, arg SearchTemplatesParams) ([]Templates, error) {
	rows, err := q.db.Query(ctx, searchTemplates,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Templates{}
	for rows.Next() {
		var i Templates
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Subject,
			&i.Content,
			&i.Variables,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTemplate = `-- name: SoftDeleteTemplate :exec
UPDATE templates
SET 
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteTemplate, id)
	return err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET 
    name = $2,
    type = $3,
    subject = $4,
    content = $5,
    variables = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, name, type, subject, content, variables, created_at, updated_at, deleted_at
`

type UpdateTemplateParams struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Subject   pgtype.Text `json:"subject"`
	Content   string      `json:"content"`
	Variables []byte      `json:"variables"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Templates, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Subject,
		arg.Content,
		arg.Variables,
	)
	var i Templates
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Subject,
		&i.Content,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
